
services:
  mongo:
    image: mongo:8-noble
    container_name: ecommerce-mongo
    restart: always
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: "${DB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
